name: test-recipes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
        - main
jobs:
  test-recipes:
    name: test-recipes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      
      - name: Install dependencies
      - run: |
          cd Engine
          bun install
      
      - name: Test recipes
      - run: export DEBUG=true && bun test